require:
  - rubocop-capybara
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Lambda:
  EnforcedStyle: literal
